project:
  type: website
  render:
    - "*.qmd"
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Summerschool"
  page-navigation: true
  navbar:
    background: light
    foreground: dark
    right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
      style: docked
      align: left
      contents:
        - section: "One could do sections like this"
          contents:
          - text: "05 Turbulence"
            href: 05_Turbulence/index.qmd
          - text: "05 Turbulence"
            href: 05_Turbulence/index.qmd
        - section: "One could do sections like this"
          contents:
          - text: "05 Turbulence"
            href: 05_Turbulence/index.qmd
          - text: "05 Turbulence"
            href: 05_Turbulence/index.qmd     
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; 2025, Lukas Arnold"

format: 
  html:
    theme: [default]
    toc: false
    